
# Name of workflow
name: lint

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2

      - name: Run linter
        run: make lint
